import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// ── Types ─────────────────────────────────────────────────────────────────────
export interface RecipePDFData {
  name: string;
  description?: string;
  authorName: string;
  soapType: "solid" | "liquid";
  batchGrams: number;
  oils: { name: string; pct: number; grams: number }[];
  superfat: number;
  naohWeight: number;
  waterAmount: number;
  lyePurity: number;
  dilutionRatio?: number;
  scores: {
    bubblyLather: number; creamyLather: number; cleansing: number;
    condition: number; hardness: number; longevity: number; iodine: number; ins: number;
  };
  fa: {
    lauric: number; myristic: number; palmitic: number; stearic: number;
    ricinoleic: number; oleic: number; linoleic: number; linolenic: number;
  };
  additives: { name: string; amount: number; unit: string; addAt: string }[];
  aiGenerated: boolean;
  tags?: string[];
}

// ── Colors — clean light/print theme ────────────────────────────────────────
const C = {
  black:    [30,  30,  30]  as [number,number,number],
  heading:  [40,  40,  40]  as [number,number,number],
  body:     [60,  60,  60]  as [number,number,number],
  muted:    [120, 120, 120] as [number,number,number],
  light:    [180, 180, 180] as [number,number,number],
  hairline: [220, 220, 220] as [number,number,number],
  bg:       [248, 247, 245] as [number,number,number],  // off-white section bg
  accent:   [156, 116, 42]  as [number,number,number],  // gold
  green:    [46,  125, 50]  as [number,number,number],
  amber:    [198, 110, 20]  as [number,number,number],
  white:    [255, 255, 255] as [number,number,number],
};

const round = (n: number, d = 2) => parseFloat(n.toFixed(d));

// ── Score bar — clean light style ────────────────────────────────────────────
function drawScoreBar(
  doc: jsPDF, label: string, value: number,
  ideal: [number,number], recommended: string,
  x: number, y: number, w: number
): void {
  const inRange = value >= ideal[0] && value <= ideal[1];
  const barColor = inRange ? C.green : C.amber;

  // Label
  doc.setFontSize(8.5);
  doc.setTextColor(...C.body);
  doc.setFont("helvetica", "normal");
  doc.text(label, x, y + 3);

  // Track bg
  const bx = x + 52, bw = w - 110, bh = 5;
  doc.setFillColor(...C.hairline);
  doc.roundedRect(bx, y - 1, bw, bh, 1, 1, "F");

  // Ideal range band
  const idealX = bx + (ideal[0] / 100) * bw;
  const idealW = ((ideal[1] - ideal[0]) / 100) * bw;
  doc.setFillColor(inRange ? 200 : 230, inRange ? 230 : 220, inRange ? 200 : 200);
  doc.roundedRect(idealX, y - 1, idealW, bh, 1, 1, "F");

  // Fill bar
  doc.setFillColor(...barColor);
  const fillW = Math.max(Math.min(value, 100) / 100 * bw, 0);
  if (fillW > 0) doc.roundedRect(bx, y - 1, fillW, bh, 1, 1, "F");

  // Value
  doc.setFontSize(8.5);
  doc.setTextColor(...barColor);
  doc.setFont("helvetica", "bold");
  doc.text(`${Math.round(value)}`, bx + bw + 3, y + 3);

  // Recommended range
  doc.setFontSize(7.5);
  doc.setTextColor(...C.muted);
  doc.setFont("helvetica", "normal");
  doc.text(recommended, bx + bw + 18, y + 3);
}

// ── Section header ────────────────────────────────────────────────────────────
function sectionHeader(doc: jsPDF, title: string, y: number, pageW: number): number {
  doc.setFillColor(...C.bg);
  doc.rect(14, y, pageW - 28, 9, "F");
  doc.setDrawColor(...C.hairline);
  doc.setLineWidth(0.3);
  doc.rect(14, y, pageW - 28, 9, "S");
  doc.setFontSize(8.5);
  doc.setTextColor(...C.accent);
  doc.setFont("helvetica", "bold");
  doc.text(title.toUpperCase(), 18, y + 6);
  doc.setFont("helvetica", "normal");
  return y + 13;
}

// ── Divider line ──────────────────────────────────────────────────────────────
function divider(doc: jsPDF, y: number, pageW: number): void {
  doc.setDrawColor(...C.hairline);
  doc.setLineWidth(0.3);
  doc.line(14, y, pageW - 14, y);
}

// ── Main PDF generator ────────────────────────────────────────────────────────
export async function generateRecipePDF(data: RecipePDFData): Promise<void> {
  const doc   = new jsPDF({ unit: "mm", format: "a4", compress: true });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const M     = 14; // margin
  let y       = 0;

  const newPage = () => {
    doc.addPage();
    doc.setFontSize(7.5);
    doc.setTextColor(...C.muted);
    doc.setFont("helvetica", "normal");
    doc.text(
      `Generated by SoapCalcAI · Handle lye with care · soapcalcai.com`,
      M, pageH - 7
    );
    doc.text(`Page ${doc.getNumberOfPages()}`, pageW - M, pageH - 7, { align: "right" });
    y = 18;
  };

  const checkSpace = (needed: number) => {
    if (y + needed > pageH - 16) newPage();
  };

  // ══════════════════════════════════════════════════════════════════════════
  // PAGE 1 — Header + Totals + Oils
  // ══════════════════════════════════════════════════════════════════════════

  // Header band
  doc.setFillColor(...C.bg);
  doc.rect(0, 0, pageW, 38, "F");

  // Gold left accent bar
  doc.setFillColor(...C.accent);
  doc.rect(0, 0, 3, 38, "F");

  // Brand
  doc.setFontSize(9);
  doc.setTextColor(...C.accent);
  doc.setFont("helvetica", "bold");
  doc.text("SOAPCALCAI", M + 2, 11);

  // Soap type badge (right)
  const badge = data.soapType === "liquid" ? "LIQUID SOAP (KOH)" : "SOLID BAR (NaOH)";
  doc.setFontSize(7.5);
  doc.setTextColor(...C.muted);
  doc.setFont("helvetica", "normal");
  doc.text(badge, pageW - M, 11, { align: "right" });

  // Recipe name
  doc.setFontSize(20);
  doc.setTextColor(...C.heading);
  doc.setFont("helvetica", "bold");
  doc.text(data.name, M + 2, 24);

  // Author + date
  doc.setFontSize(8);
  doc.setTextColor(...C.muted);
  doc.setFont("helvetica", "normal");
  const dateStr = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  doc.text(`by ${data.authorName}  ·  ${dateStr}${data.aiGenerated ? "  ·  ✦ AI Generated" : ""}`, M + 2, 32);

  // Gold bottom line
  doc.setFillColor(...C.accent);
  doc.rect(0, 38, pageW, 0.7, "F");

  y = 46;

  // Description
  if (data.description?.trim()) {
    doc.setFontSize(9);
    doc.setTextColor(...C.body);
    const lines = doc.splitTextToSize(data.description.trim(), pageW - M * 2);
    doc.text(lines, M, y);
    y += lines.length * 5 + 4;
  }

  // ── Recipe Totals ──────────────────────────────────────────────────────────
  y = sectionHeader(doc, "Recipe Totals", y, pageW);

  const lyeConc    = data.naohWeight / (data.naohWeight + data.waterAmount) * 100;
  const lyeRatio   = data.waterAmount / data.naohWeight;
  const batchTotal = data.batchGrams + data.naohWeight + data.waterAmount;
  const lye        = data.soapType === "liquid" ? "KOH" : "NaOH";

  const totals: [string, string, string, string][] = [
    ["Oil Weight",         `${round(data.batchGrams, 0)} g`,
     "Super Fat",          `${data.superfat}%`],
    [`${lye} Weight`,      `${round(data.naohWeight, 2)} g  @ ${data.lyePurity}% purity`,
     "Lye Concentration",  `${round(lyeConc, 1)}%`],
    ["Liquid Required",    `${round(data.waterAmount, 1)} g`,
     "Liquid : Lye Ratio", `${round(lyeRatio, 2)}:1`],
    ["Total Batch Weight", `${round(batchTotal, 0)} g`,
     "Sat : Unsat",        (() => {
       const sat   = data.fa.lauric+data.fa.myristic+data.fa.palmitic+data.fa.stearic;
       const unsat = data.fa.oleic+data.fa.linoleic+data.fa.linolenic+data.fa.ricinoleic;
       return `${Math.round(sat)}:${Math.round(unsat)}`;
     })()],
    ...(data.soapType === "liquid" && data.dilutionRatio ? [[
      "Dilution Ratio",   `1 : ${data.dilutionRatio}`,
      "Finished Soap",    `${round(batchTotal * (1 + data.dilutionRatio), 0)} g`,
    ] as [string,string,string,string]] : []),
  ];

  totals.forEach(([l1, v1, l2, v2], i) => {
    if (i > 0) {
      doc.setDrawColor(...C.hairline);
      doc.setLineWidth(0.2);
      doc.line(M, y - 1, pageW - M, y - 1);
    }
    // Left col
    doc.setFontSize(8.5);
    doc.setTextColor(...C.muted);
    doc.setFont("helvetica", "normal");
    doc.text(l1, M, y + 4);
    doc.setTextColor(...C.body);
    doc.setFont("helvetica", "bold");
    doc.text(v1, M + 52, y + 4);
    // Right col
    doc.setTextColor(...C.muted);
    doc.setFont("helvetica", "normal");
    doc.text(l2, pageW / 2 + 4, y + 4);
    doc.setTextColor(...C.body);
    doc.setFont("helvetica", "bold");
    doc.text(v2, pageW / 2 + 56, y + 4);
    doc.setFont("helvetica", "normal");
    y += 9;
  });

  y += 4;

  // ── Oil Formula ────────────────────────────────────────────────────────────
  checkSpace(20);
  y = sectionHeader(doc, "Oil Formula", y, pageW);

  autoTable(doc, {
    startY: y,
    margin: { left: M, right: M },
    head: [["Oil", "Weight (g)", "% of Batch"]],
    body: data.oils.map(o => [
      `${o.name} Oil`,
      `${round(o.grams, 0)}`,
      `${round(o.pct, 1)}%`,
    ]),
    foot: [["TOTAL", `${round(data.batchGrams, 0)}`, "100%"]],
    styles:      { fontSize: 8.5, cellPadding: 3.5, textColor: C.body as any, lineColor: C.hairline as any, lineWidth: 0.2 },
    headStyles:  { fillColor: C.bg as any, textColor: C.accent as any, fontStyle: "bold", fontSize: 8, lineColor: C.hairline as any },
    footStyles:  { fillColor: C.bg as any, textColor: C.heading as any, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [252, 252, 251] as any },
    bodyStyles:  { fillColor: C.white as any },
    columnStyles: {
      0: { cellWidth: 70 },
      1: { halign: "right", cellWidth: 30 },
      2: { halign: "right", cellWidth: 30 },
    },
  });

  y = (doc as any).lastAutoTable.finalY + 6;

  // ── Custom Additives ───────────────────────────────────────────────────────
  if (data.additives.length > 0) {
    checkSpace(20);
    y = sectionHeader(doc, "Custom Additives", y, pageW);
    autoTable(doc, {
      startY: y,
      margin: { left: M, right: M },
      head: [["Additive", "Amount", "When to Add"]],
      body: data.additives.map(a => [
        a.name || "—",
        `${a.amount} ${a.unit}`,
        a.addAt === "liquid" ? "With liquid" : a.addAt === "fats" ? "With fats" : "At trace",
      ]),
      styles:      { fontSize: 8.5, cellPadding: 3.5, textColor: C.body as any, lineColor: C.hairline as any, lineWidth: 0.2 },
      headStyles:  { fillColor: C.bg as any, textColor: C.accent as any, fontStyle: "bold", fontSize: 8, lineColor: C.hairline as any },
      bodyStyles:  { fillColor: C.white as any },
      alternateRowStyles: { fillColor: [252, 252, 251] as any },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // ══════════════════════════════════════════════════════════════════════════
  // PAGE 2 — Properties + Fatty Acids + Instructions + Safety
  // ══════════════════════════════════════════════════════════════════════════
  newPage();

  // ── Recipe Properties ──────────────────────────────────────────────────────
  y = sectionHeader(doc, "Recipe Properties", y, pageW);

  const scoreItems: [string, number, [number,number], string][] = [
    ["Bubbly Lather",  data.scores.bubblyLather,  [14,46],   "14 - 46"],
    ["Cleansing",      data.scores.cleansing,      [12,22],   "12 - 22"],
    ["Condition",      data.scores.condition,      [44,69],   "44 - 69"],
    ["Hardness",       data.scores.hardness,       [29,54],   "29 - 54"],
    ["Longevity",      data.scores.longevity,      [25,50],   "25 - 50"],
    ["Creamy Lather",  data.scores.creamyLather,   [16,48],   "16 - 48"],
    ["Iodine",         data.scores.iodine,         [41,70],   "41 - 70"],
    ["INS",            data.scores.ins,            [136,165], "136 - 165"],
  ];

  const bw2 = (pageW - M * 2) / 2 - 6;
  scoreItems.forEach(([label, value, ideal, rec], i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const bx  = M + col * (bw2 + 12);
    const by  = y + row * 12;
    checkSpace(14);
    drawScoreBar(doc, label, value, ideal, rec, bx, by, bw2);
  });

  y += Math.ceil(scoreItems.length / 2) * 12 + 8;

  // ── Fatty Acids ────────────────────────────────────────────────────────────
  checkSpace(60);
  y = sectionHeader(doc, "Fatty Acids %", y, pageW);

  autoTable(doc, {
    startY: y,
    margin: { left: M, right: M },
    head: [["Fatty Acid", "% in Blend", "Type", "Effect on Soap"]],
    body: (Object.entries(data.fa) as [string, number][]).map(([key, val]) => {
      const info: Record<string, [string, string]> = {
        lauric:     ["Saturated",   "Hard bar, big bubbly lather, cleansing"],
        myristic:   ["Saturated",   "Hardness, fluffy lather, cleansing"],
        palmitic:   ["Saturated",   "Hard, long-lasting, creamy lather"],
        stearic:    ["Saturated",   "Very hard, stable, creamy lather"],
        ricinoleic: ["Unsaturated", "Conditioning, glossy, lather boost"],
        oleic:      ["Unsaturated", "Conditioning, soft bar, skin-loving"],
        linoleic:   ["Unsaturated", "Very conditioning, moisturizing"],
        linolenic:  ["Unsaturated", "Conditioning, but shortens shelf life"],
      };
      const [type, effect] = info[key] ?? ["—", "—"];
      return [
        key.charAt(0).toUpperCase() + key.slice(1),
        `${round(val, 1)}%`,
        type,
        effect,
      ];
    }),
    styles:      { fontSize: 8, cellPadding: 2.8, textColor: C.body as any, lineColor: C.hairline as any, lineWidth: 0.2 },
    headStyles:  { fillColor: C.bg as any, textColor: C.accent as any, fontStyle: "bold", fontSize: 8, lineColor: C.hairline as any },
    bodyStyles:  { fillColor: C.white as any },
    alternateRowStyles: { fillColor: [252, 252, 251] as any },
    columnStyles: { 0: { cellWidth: 28 }, 1: { cellWidth: 24, halign: "right" }, 2: { cellWidth: 28 }, 3: {} },
  });

  y = (doc as any).lastAutoTable.finalY + 8;

  // ── Batch Instructions ─────────────────────────────────────────────────────
  checkSpace(20);
  y = sectionHeader(doc, "Batch Instructions", y, pageW);

  const isLiquid = data.soapType === "liquid";
  const steps = isLiquid ? [
    { n:"1.", title:"Prepare workspace",    detail:"Wear gloves, goggles, and long sleeves. Clear workspace of food and children." },
    { n:"2.", title:"Measure oils",         detail:`Weigh out: ${data.oils.map(o=>`${o.name} ${round(o.grams,0)}g`).join(", ")}. Melt solid oils first.` },
    { n:"3.", title:"Prepare KOH lye",     detail:`Slowly add ${round(data.naohWeight,2)}g KOH (${data.lyePurity}% purity) to ${round(data.waterAmount,1)}g distilled water. NEVER add water to lye.` },
    { n:"4.", title:"Combine",             detail:"When both oils and lye are ~50–60°C, pour lye into oils. Stick blend to trace." },
    { n:"5.", title:"Cook (Hot Process)",  detail:"Cook at 65–80°C for 1–2 hours until neutral pH (7–8 on pH strips)." },
    { n:"6.", title:"Dilute",              detail:`Dissolve paste in hot distilled water at 1:${data.dilutionRatio ?? 2.5} ratio. Stir until clear.` },
    { n:"7.", title:"Add additives",       detail:data.additives.length > 0 ? `Add: ${data.additives.map(a=>`${a.name} (${a.amount}${a.unit})`).join(", ")}.` : "No additives for this recipe." },
    { n:"8.", title:"Bottle",              detail:"Pour into bottles. Allow 24–48h to clarify before use." },
  ] : [
    { n:"1.", title:"Prepare workspace",        detail:"Wear gloves, goggles, and long sleeves. Prepare molds, thermometer, and stick blender." },
    { n:"2.", title:"Measure oils",             detail:`Weigh out: ${data.oils.map(o=>`${o.name} ${round(o.grams,0)}g`).join(", ")}. Melt solid oils gently.` },
    { n:"3.", title:"Prepare NaOH lye",         detail:`Slowly add ${round(data.naohWeight,2)}g NaOH (${data.lyePurity}% purity) to ${round(data.waterAmount,1)}g cool distilled water. NEVER add water to lye. Stir until dissolved.` },
    { n:"4.", title:"Combine at temperature",   detail:"When both oils and lye are 40–50°C (within 10°C), pour lye into oils while stick blending." },
    { n:"5.", title:"Trace",                    detail:"Stick blend in short bursts until light trace (batter thickens like thin pudding)." },
    { n:"6.", title:"Add additives",            detail:data.additives.filter(a=>a.addAt==="trace").length > 0 ? `At trace: ${data.additives.filter(a=>a.addAt==="trace").map(a=>`${a.name} (${a.amount}${a.unit})`).join(", ")}.` : "No trace additives for this recipe." },
    { n:"7.", title:"Pour into molds",          detail:"Pour into molds. Tap to release bubbles. Cover and insulate 24–48h." },
    { n:"8.", title:"Unmold & cure",            detail:"Unmold after 24–48h. Cure 4–6 weeks in ventilated area. Curing improves hardness and lather." },
  ];

  steps.forEach(({ n, title, detail }) => {
    checkSpace(14);
    doc.setFontSize(8.5);
    doc.setTextColor(...C.accent);
    doc.setFont("helvetica", "bold");
    doc.text(n, M, y + 4);
    doc.setTextColor(...C.heading);
    doc.text(title, M + 7, y + 4);
    y += 6;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...C.body);
    doc.setFontSize(8);
    const lines = doc.splitTextToSize(detail, pageW - M * 2 - 10);
    doc.text(lines, M + 7, y);
    y += lines.length * 4.5 + 4;
  });

  // ── Safety Notes ───────────────────────────────────────────────────────────
  checkSpace(50);
  y += 2;
  y = sectionHeader(doc, "⚠ Safety Notes", y, pageW);

  // Light amber border box
  doc.setFillColor(255, 249, 235);
  doc.setDrawColor(198, 150, 50);
  doc.setLineWidth(0.4);
  doc.roundedRect(M, y, pageW - M * 2, 52, 2, 2, "FD");

  const safetyNotes = [
    "Always add LYE TO WATER — never water to lye. This causes a violent, dangerous reaction.",
    "Wear PPE: chemical-resistant gloves, safety goggles, and long sleeves at all times.",
    "Work in a well-ventilated area. Lye fumes are caustic — avoid inhaling.",
    "Keep children and pets away from the workspace during the entire process.",
    "Use dedicated soap-making equipment — never reuse for food after lye contact.",
    "Skin contact with lye: rinse with large amounts of cool water for 15+ minutes.",
    isLiquid
      ? "KOH soap: cook to neutral pH before diluting. Test with pH strips (target 7–9)."
      : "Cold process soap requires 4–6 weeks cure time. Freshly made soap is still caustic.",
  ];

  let sy = y + 6;
  safetyNotes.forEach(note => {
    doc.setFontSize(7.5);
    doc.setTextColor(140, 90, 20);
    doc.setFont("helvetica", "bold");
    doc.text("•", M + 4, sy);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 70, 10);
    const lines = doc.splitTextToSize(note, pageW - M * 2 - 14);
    doc.text(lines, M + 9, sy);
    sy += lines.length * 4 + 2;
  });

  // ── Notes ──────────────────────────────────────────────────────────────────
  if (data.description?.trim()) {
    y += 58;
    checkSpace(20);
    y = sectionHeader(doc, "Notes", y, pageW);
    doc.setFontSize(8.5);
    doc.setTextColor(...C.body);
    const lines = doc.splitTextToSize(data.description.trim(), pageW - M * 2);
    doc.text(lines, M, y);
    y += lines.length * 5;
  }

  // ── Footer on last page ────────────────────────────────────────────────────
  doc.setFontSize(7.5);
  doc.setTextColor(...C.muted);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by SoapCalcAI · Handle lye with care · soapcalcai.com", M, pageH - 7);
  doc.text(`Page ${doc.getNumberOfPages()}`, pageW - M, pageH - 7, { align: "right" });

  // Gold top line on last page
  doc.setFillColor(...C.accent);
  doc.rect(0, 0, pageW, 0.7, "F");

  // ── Save ──────────────────────────────────────────────────────────────────
  const filename = `${data.name.replace(/[^a-z0-9]/gi,"_").toLowerCase()}_recipe.pdf`;
  doc.save(filename);
}